# Generated by Django 5.2.6 on 2025-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuariolist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15, verbose_name='Usuario')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña')),
            ],
        ),
    ]
